variable "aws_session_token" {
  description = "Temporary session token used to create instances"
}

variable "aws_access_key" {
  description = "Accesss key generated by AWS STS Refresher Tool"
}

variable "aws_secret_key" {
  description = "Access secret key generated by AWS STS Refresher Tool"
}

variable "region" {
  description = "Specifies region where AWS resources will be deployed"
}
